language: node_js

node_js:
  - 8

script:
  - yarn tsc
  - yarn test -- --ci

before_script:
  - yarn

before_deploy:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
